### ISSUE TITLE
Not compatible with the newest version of VS

### ISSUE THREAD

**Issue by kosiara** [Gorniv/vscode-flutter-files#2]
Unfortunatelly it says: 

Unable to install because `flutter-files` compatible with version 1.32.1 of VS is not found :( 

<img width="455" alt="screen shot 2019-03-08 at 5 24 47 pm" src="https://user-images.githubusercontent.com/4531522/54041168-4d23cd00-41c7-11e9-92c5-05c2e2cf380b.png">

Is there a way around this?

**Comment by Gorniv** [comment]
Is fix help?
