### ISSUE TITLE
Create custom templates

### ISSUE THREAD

**Issue by Mol0ko** [Gorniv/vscode-flutter-files#25]
Is it possible to create custom templates and use them instead of `Big Pack Bloc` and `Small Pack Bloc`?
It would be great to use custom templates with project-specific libraries, classes, and dependencies or use other architectural templates such as MVVM, Redux etc.

P.S. Thanks for that cool VSCode extension for Flutter!

**Comment by Gorniv** [comment]
The custom command "Dynamic command" with steps from JSON(project) - is it ok?

**Comment by Gorniv** [comment]
I found https://code.visualstudio.com/api/extension-guides/command
I think it can be real)
I try to change extension this weekend

**Comment by Gorniv** [comment]
done
