### ISSUE TITLE
bug: Command '[FF] Copy templates to project' resulted in an error

### ISSUE THREAD

**Issue by Mol0ko** [Gorniv/vscode-flutter-files#32]
I got errors when trying to run any command from the latest extension version ([v3.1.1](https://github.com/Gorniv/vscode-flutter-files/releases/tag/v3.1.1)). 
Here is an example for new command `[FF] Copy templates to project`:
```
Command '[FF] New with dynamic config' resulted in an error (command 'extension.addFlutter2_Dynamic' not found)
```
<img width="505" alt="error" src="https://user-images.githubusercontent.com/24519478/106893102-1b427a80-66fe-11eb-835e-b5092671c30a.png">

I don't know how to configure VSCode extensions, but looks like it is invalid now(

**Comment by Gorniv** [comment]
please check 3.1.2

**Comment by Mol0ko** [comment]
@Gorniv 3.1.2 is ok
