### ISSUE TITLE
Imported .index guesses the wrong path

### ISSUE THREAD

**Issue by lewcianci** [Gorniv/vscode-flutter-files#6]
Hey,

Creating a new "small pack bloc" this morning for my app, up the top of the generated files it has this:

import 'package:mapman_flutter/undefined/index.dart';

Flutter can't find "undefined". Its supposed to be the name of my generated bloc I would assume.

*Disclaimer* I am a brand new flutter developer (coming from Xamarin) so I might be missing something obvious

**Comment by Gorniv** [comment]
fixed at 1.2.4
