### ISSUE TITLE
File(s) could not be created. TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by nguyenhuutinh** [Gorniv/vscode-flutter-files#7]
Cannot  create  new big  pack bloc due to this error

I'm using MacOs

**Comment by nguyenhuutinh** [comment]
another error: Error: TypeError: Cannot read property 'has' of undefined

**Comment by nathanbrizzee** [comment]
I get the same error on Windows.  This  extension worked a few days ago but recently broke.

**Comment by Gorniv** [comment]
Thank you!
This bug was reproduced without using custom templates.
1.3.2 - fixed.
Custom templates are great;)

**Comment by nguyenhuutinh** [comment]
thanks for quick support. 

btw,  Custom templates ? what is it?

**Comment by Gorniv** [comment]
@nguyenhuutinh you can copy folder 'templates' from this repository to your project and change files.
See the second gif on the readme
